version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    # Make sure 'versions' is an array
    ignore:
      - dependency-name: "io.dropwizard:dropwizard-bom"
        versions:
          - ">= 4.a"
